/*

 WONDERLEAF.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 26 x 17
   Tile set      : E:\{_}\Fatalited\gbr-gbm\gbr\wonderleaf.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define wonderleafWidth 26
#define wonderleafHeight 17
#define wonderleafBank 0

extern unsigned char wonderleaf[];

/* End of WONDERLEAF.H */
